POST http://localhost:3003/api/blogs HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1pc3NlIiwiaWQiOiI2NDYyN2QxYTA3YTM1ZWFhY2MwYjRhMTIiLCJpYXQiOjE2ODQxNzYyMjQsImV4cCI6MTY4NDE3OTgyNH0.-zMjtlxbA4FEktQSoJRiHCEazFiWULa1RmPNMPCGZ30

{
  "title": "Uusi blogi",
  "author": "Bloggaaja",
  "url": "kymysysmerkki.fi"
}